# fvwm-menu maker toml file

title = "FVWM Menu Maker"

[app_path]
path="../applications"

[owner]
name = "Ron Georgia"
handle = "Ronverbs"

[menu]
keys = ["Name", "Exec", "Terminal", "Categories", ]
categories = [
    "Desktop", "Development", "FileManager", "FileTools", "Graphics", "Monitor", "Network",
    "Office", "Settings", "System", "Terminal", "TextEditor", "Utility",
]
skip_list = [
    '/usr/local/libexec/geoclue-2.0/demos/where-am-i', '/usr/local/bin/bssh', 'bvnc',
    'lxshortcut', 'xfce4-about', 'gtk3-demo', 'xscreensaver-demo', 'pcmanfm --desktop-pref',
    '/usr/local/bin/menulibre', 'libfm-pref-apps', 'xfce4-terminal --preferences',
    '/usr/local/libexec/gcr-prompter', '/usr/local/bin/gcr-viewer', '/usr/local/bin/bvnc',
    'firefox -private-window', 'compton',
]

[short_names]
inkscape = ["New Drawing", "Inkscape"]
ristretto = ["Ristretto Image Viewer", "Ristretto"]
gimp = ["GNU Image Manipulation Program", "GIMP"]
xfburn = ["Burn Image (xfburn)", "xfburn"]
pcmanfm = ["File Manager PCManFM", "pcmanfm"]
pycharm = ["JetBrains PyCharm Professional Edition IDE", "PyCharm Pro"]
bluefish = ["Bluefish Editor", "bluefish"]











